name: Build and Deploy
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
env:
  source_file_name: dakr.link
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt-get install -y asciidoctor
          pip install -r requirements.txt

      - name: Generate QR codes
        run: python qrgen.py

      - name: Build
        run: asciidoctor ${{ env.source_file_name }}.adoc -o index.html -D build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: build